export const ADD_VIDOE_REQ = 'ADD_VIDOE_REQ';
export const ADD_VIDEO_SUC = 'ADD_VIDEO_SUC';
export const ADD_VIDEO_FAILED = 'ADD_VIDEO_FAILED';

export const FETCH_VIDEO_REQ = 'FETCH_VIDEO_REQ';
export const FETCH_VIDEO_SUC = 'FETCH_VIDEO_SUC';
export const FETCH_VIDEO_FAILED = 'FETCH_VIDEO_FAILED';

export const VIDEO_ID_REQ = 'VIDEO_BY_ID';
export const VIDEO_ID_SUC = 'VIDEO_ID_SUC';
export const VIDEO_ID_FAIL = 'VIDEO_ID_FAIL';

export const FETCH_COMMENT_REQ = 'FETCH_COMMENT_REQ';
export const FETCH_COMMENT_SUC = 'FETCH_COMMENT_SUC';
export const FETCH_COMMENT_FAIL = 'FETCH_COMMENT_FAIL';

export const DELETE_VIDEO_REQ = 'DELETE_VIDEO_REQ';
export const DELETE_VIDEO_SUC = 'DELETE_VIDEO_SUC';
export const DELETE_VIDEO_FAIL = 'DELETE_VIDEO_FAIL';

export const EDIT_VIDEO_REQ = 'EDIT_VIDEO_REQ';
export const EDIT_VIDEO_SUC = 'EDIT_VIDEO_SUC';
export const EDIT_VIDEO_FAIL = 'EDIT_VIDEO_FAIL';