export const SIGNUP_REQ = 'SIGNUP_REQ';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const CHECK_USERNAME_REQ = 'CHECK_USERNAME_REQ';
export const CHECK_USERNAME_SUCCESS = 'CHECK_USERNAME_SUCCESS';
export const CHECK_USERNAME_FAILED = 'CHECK_USERANEM_FAILED';