export const COMMENT_REQ = 'COMMENT_REQ';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
export const COMMENT_FAILED = 'COMMENT_FAILED';

export const FETCH_COMMENT_REQ = 'FETCH_COMMENT_REQ';
export const FETCH_COMMENT_SUC = 'FETCH_COMMENT_SUC';
export const FETCH_COMMENT_FAILED = 'FETCH_COMMENT_FAILED';