export const FETCH_VIDEO_REQ = 'FETCH_VIDEO_REQ';
export const FETCH_VIDEO_SUCCESS = 'FETCH_VIDEO_SUCCESS';
export const FETCH_VIDEO_FAILED = 'FETCH_VIDEO_FAILED';

export const FETCH_ID_REQ = 'FETCH_ID_REQ';
export const FETCH_ID_SUCCESS = 'FETCH_ID_SUCCESS';
export const FETCH_ID_FAILED =  'FETCH_ID_FAILED';
