export const FETCH_VIDEO_REQ = 'FETCH_VIDEO_REQ';
export const FETCH_VIDEO_SUCCESS = 'FETCH_VIDEO_SUCCESS';
export const FETCH_VIDEO_FAILED = 'FETCH_VIDEO_FAILED';

export const FETCH_ID_REQ = 'FETCH_ID_REQ';
export const FETCH_ID_SUCCESS = 'FETCH_ID_SUCCESS';
export const FETCH_ID_FAILED =  'FETCH_ID_FAILED';

export const FETCH_NEW_REQ = 'FETCH_NEW_REQ';
export const FETCH_NEW_SUC = 'FETCH_NEW_SUC';
export const FETCH_NEW_FAILED = 'FETCH_NEW_FAILED';

export const FETCH_GENRE_REQ = "FETCH_GENRE_REQ";
export const FETCH_GENRE_SUC = "FETCH_GENRE_SUC";
export const FETCH_GENRE_FAIL = "FETCH_GENRE_FAIL";
